import Head from 'next/head'
// import { ServerApplication, Button } from 'react-rainbow-components';
import Button from '@button';
import ServerApplication from 'react-rainbow-components/components/ServerApplication/index.js';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ServerApplication>
          <Button label="Hello World!" />
        </ServerApplication>
      </main>
    </>
  )
}
